# Generated by Django 5.2.1 on 2025-06-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='target_time',
            field=models.DateTimeField(),
        ),
    ]
